language: php

# Container-based infrastructure
sudo: false

# Cache composer
cache:
  directories:
    - $HOME/.composer/cache

php:
# no extensive travis testing before we have some real tests and project stable
#  - 5.4
#  - 5.5
#  - 5.6
  - 7.2
#  - hhvm

# optionally specify a list of environments, for example to test different RDBMS
env:
- DB=mysql
- DB=pgsql
#- DB=mariadb

install:
  - composer install

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
- if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS flyspray_test;" -U postgres; fi
- if [[ "$DB" == "pgsql" ]]; then psql -c "CREATE DATABASE flyspray_test;" -U postgres; fi
- if [[ "$DB" == "mysql" ]]; then mysql -uroot -e "CREATE DATABASE IF NOT EXISTS flyspray_test DEFAULT CHARSET=utf8mb4;"; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration phpunit_$DB.xml --coverage-text
