<?php
$permicons=array(
'view_tasks'=>'<span class="fa-stack"><span class="fas fa-list-check fa-stack-2x"></span><span class="fas fa-eye fa-stack"></span></span>',
'view_groups_tasks'=>'<span class="fa-stack"><span class="fas fa-list-check fa-stack-2x"></span><span class="fas fa-eye fa-stack"></span></span>',
'view_own_tasks'=>'<span class="fa-stack"><span class="fas fa-list-check fa-stack-2x"></span><span class="fas fa-eye fa-stack"></span></span>',
'view_roadmap'=>'<span class="fa-stack"><span class="fas fa-road fa-stack-2x"></span><span class="fas fa-eye fa-stack"></span></span>',
'view_history'=>'<span class="fa-stack"><span class="fas fa-clock-rotate-left fa-stack-2x"></span><span class="fas fa-eye fa-stack"></span></span>',
'view_reports'=>'<span class="fa-stack"><span class="fas fa-chart-line fa-stack-2x"></span><span class="fas fa-eye fa-stack"></span></span>',
'view_estimated_effort'=>'<span class="fa-stack"><span class="far fa-clock fa-stack-2x"></span><span class="fas fa-eye fa-stack"></span></span>',
'view_current_effort_done'=>'<span class="fa-stack"><span class="far fa-clock fa-stack-2x"></span><span class="fas fa-eye fa-stack"></span></span>',
'track_effort'=>'<span class="fa-stack"><span class="far fa-clock fa-stack-2x"></span><span class="fas fa-eye fa-stack"></span></span>',
'open_new_tasks'=>'<span class="fa-stack"><span class="fas fa-list-check fa-stack-2x"></span><span class="fas fa-plus fa-stack"></span></span>',
'add_multiple_tasks'=>'<span class="fa-stack"><span class="fas fa-list-check fa-stack-2x"></span><span class="fas fa-plus fa-stack"></span></span>',
'modify_own_tasks'=>'<span class="fa-stack"><span class="fas fa-list-check fa-stack-2x"></span><span class="fas fa-pencil fa-stack"></span></span>',
'modify_all_tasks'=>'<span class="fa-stack"><span class="fas fa-list-check fa-stack-2x"></span><span class="fas fa-pencil fa-stack"></span></span>',
'close_own_tasks'=>'<span class="fas fa-check fa-2x"></span>',
'close_other_tasks'=>'<span class="fas fa-check fa-2x"></span>',
'create_attachments'=>'<span class="fa-stack"><span class="fas fa-paperclip fa-stack-2x"></span><span class="fas fa-plus fa-stack"></span></span>',
'delete_attachments'=>'<span class="fa-stack"><span class="fas fa-paperclip fa-stack-2x"></span><span class="fas fa-xmark fa-stack"></span></span>',
'assign_to_self'=>'<span class="fa-stack"><span class="fas fa-hand-point-right fa-stack-2x"></span></span>',
'assign_others_to_self'=>'<span class="fa-stack"><span class="fas fa-hand-point-right  fa-stack-2x"></span></span>',
'edit_assignments'=>'<span class="fa-stack"><span class="fas fa-hand-point-right fa-stack-2x"></span><span class="fas fa-pencil fa-stack"></span></span>',
'add_votes'=>'<span class="fa-stack"><span class="far fa-star fa-stack-2x"></span><span class="fas fa-plus fa-stack"></span></span>',
'view_comments'=>'<span class="fa-stack"><span class="fas fa-comments fa-stack-2x"></span><span class="fas fa-eye fa-stack"></span></span>',
'add_comments'=>'<span class="fa-stack"><span class="fas fa-comments fa-stack-2x"></span><span class="fas fa-plus fa-stack"></span></span>',
'edit_comments'=>'<span class="fa-stack"><span class="fas fa-comments fa-stack-2x"></span><span class="fas fa-pencil fa-stack"></span></span>',
'edit_own_comments'=>'<span class="fa-stack"><span class="fas fa-comments fa-stack-2x"></span><span class="fas fa-pencil fa-stack"></span></span>',
'delete_comments'=>'<span class="fa-stack"><span class="fas fa-comments fa-stack-2x"></span><span class="fas fa-xmark fa-stack"></span></span>'
);
?>
