<?php
$permicons = array(
	'view_tasks'=>'<span class="fa-stack"><span class="fas fa-list-check fa-stack-2x"></span><span class="fas fa-eye fa-stack-1x"></span></span>',
	'view_groups_tasks'=>'<span class="fa-stack"><span class="fas fa-list-check fa-stack-2x"></span><span class="fas fa-user-group fa-stack-1x"></span></span>',
	'view_own_tasks'=>'<span class="fa-stack"><span class="fas fa-list-check fa-stack-2x"></span><span class="fas fa-user fa-stack-1x"></span></span>',
	'view_roadmap'=>'<span class="fa-stack"><span class="fas fa-road fa-stack-2x"></span><span class="fas fa-eye fa-stack-1x"></span></span>',
	'view_history'=>'<span class="fa-stack"><span class="fas fa-clock-rotate-left fa-stack-2x"></span><span class="fas fa-eye fa-stack-1x"></span></span>',
	'view_reports'=>'<span class="fa-stack"><span class="fas fa-chart-line fa-stack-2x"></span><span class="fas fa-eye fa-stack-1x"></span></span>',
	'view_estimated_effort'=>'<span class="fa-stack"><span class="fas fa-stopwatch fa-stack-2x"></span><span class="fas fa-eye fa-stack-1x"></span></span>',
	'view_current_effort_done'=>'<span class="fa-stack"><span class="fas fa-stopwatch fa-stack-2x"></span><span class="fas fa-calendar-check fa-stack-1x"></span></span>',
	'track_effort'=>'<span class="fa-stack"><span class="fas fa-stopwatch fa-stack-2x"></span><span class="fas fa-user fa-stack-1x"></span></span>',
	'open_new_tasks'=>'<span class="fa-stack"><span class="fas fa-list-check fa-stack-2x"></span><span class="fas fa-circle-plus fa-stack-1x"></span></span>',
	'add_multiple_tasks'=>'<span class="fa-stack"><span class="fas fa-list-check fa-stack-2x"></span><span class="fas fa-folder-plus fa-stack-1x"></span></span>',
	'manage_project'=>'<span class="fa-stack"><span class="fas fa-user-tie fa-stack-2x"></span></span>',
	'is_admin'=>'<span class="fa-stack"><span class="fas fa-user-shield fa-stack-2x"></span></span>',
    'group_open'=>'<span class="fa-stack"><span class="fas fa-door-open fa-stack-2x"></span><span class="fas fa-circle-check fa-stack-1x"></span></span>',
	'modify_own_tasks'=>'<span class="fa-stack"><span class="fas fa-list-check fa-stack-2x"></span><span class="fas fa-pencil fa-stack-1x"></span></span>',
	'modify_all_tasks'=>'<span class="fa-stack"><span class="fas fa-list-check fa-stack-2x"></span><span class="fas fa-hand-point-right fa-stack-1x"></span></span>',
	'close_own_tasks'=>'<span class="fa-stack"><span class="fas fa-clipboard-check fa-stack-2x"></span><span class="fas fa-user fa-stack-1x"></span></span>',
	'close_other_tasks'=>'<span class="fa-stack"><span class="fas fa-clipboard-check fa-stack-2x"></span><span class="fas fa-hand-point-right fa-stack-1x"></span></span>',
	'create_attachments'=>'<span class="fa-stack"><span class="fas fa-paperclip fa-stack-2x"></span><span class="fas fa-circle-plus fa-stack-1x"></span></span>',
	'delete_attachments'=>'<span class="fa-stack"><span class="fas fa-paperclip fa-stack-2x"></span><span class="fas fa-circle-xmark fa-stack-1x"></span></span>',
	'assign_to_self'=>'<span class="fa-stack"><span class="fas fa-hand-point-right fa-stack-2x"></span><span class="fas fa-circle-exclamation fa-stack-1x"></span></span>',
	'assign_others_to_self'=>'<span class="fa-stack"><span class="fas fa-hand-point-right  fa-stack-2x"></span><span class="fas fa-user fa-stack-1x"></span></span>',
	'edit_assignments'=>'<span class="fa-stack"><span class="fas fa-hand-point-right fa-stack-2x"></span><span class="fas fa-pencil fa-stack-1x"></span></span>',
	'add_votes'=>'<span class="fa-stack"><span class="fas fa-star fa-stack-2x"></span><span class="fas fa-circle-plus fa-stack-1x"></span></span>',
	'view_comments'=>'<span class="fa-stack"><span class="fas fa-comments fa-stack-2x"></span><span class="fas fa-eye fa-stack-1x"></span></span>',
	'add_comments'=>'<span class="fa-stack"><span class="fas fa-comments fa-stack-2x"></span><span class="fas fa-circle-plus fa-stack-1x"></span></span>',
	'edit_comments'=>'<span class="fa-stack"><span class="fas fa-comments fa-stack-2x"></span><span class="fas fa-pencil fa-stack-1x"></span></span>',
	'edit_own_comments'=>'<span class="fa-stack"><span class="fas fa-comments fa-stack-2x"></span><span class="fas fa-user fa-stack-1x"></span></span>',
	'delete_comments'=>'<span class="fa-stack"><span class="fas fa-comments fa-stack-2x"></span><span class="fas fa-circle-xmark fa-stack-1x"></span></span>'
);
?>
